Add Dockerfile for Node 20.9.0
swissgrc/docker-azure-pipelines-node20-net7 pull request #2
Opened 2023-10-27 07:20 UTC by pascalberger

Add Dockerfile for Node 20.9.0

2023-10-27 09:40 UTC, soebbel approved these changes

2023-10-27 10:40 UTC, Xzelsius requested changes

2023-10-27 10:40 UTC, Xzelsius commented on README.md
> +| 20.9.0-net7      | [Node.js 20.9.0](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#may-23-2023) | swissgrc/azure-pipelines-dotnet:7.0.402   | 20.9.0  | ![Docker Image Size (tag
Wrong release notes link

2023-10-27 19:07 UTC, pascalberger commented on README.md
> +| 20.9.0-net7      | [Node.js 20.9.0](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#may-23-2023) | swissgrc/azure-pipelines-dotnet:7.0.402   | 20.9.0  | ![Docker Image Size (tag
@Xzelsius Ready for another review

2023-10-30 13:34 UTC, Xzelsius approved these changes

2023-10-30 13:47 UTC, merged